### PR TITLE
OOP school library: unit tests

### PR DESCRIPTION
**Pull request by fmanimashaun**
# Unit Tests for School Library Project

## Description

This pull request introduces comprehensive unit tests for all methods in the following classes of our School Library project:

- `Person`
- `Student`
- `Teacher`
- `Book`
- `Rental`
- `Classroom`
- `Decorator`
- `CapitalizeDecorator`
- `TrimmerDecorator`

### Changes

- Added unit tests for all methods in the above classes.

### CODE REVIEW

**Review by Munsa1 — CHANGES_REQUESTED** [review]
Hi @fmanimashaun @Ademola-coding , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a PR with co-authored commits.
Co-authoring is fantastic, but to ensure equal contribution to the codebase, let's aim for commits from each partner in the actual codebase! Remember, your contributions are awesome, but they won't count toward the codebase collaboration. Let's rock this project together! 💻💬🚀

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by fmanimashaun** [comment]
I think you need to be more fair with your assessment @Munsa1. My coding partner @Ademola-coding  and I have been working collaboratively, and you claimed that because we opted to use a collaborating tool, our work is invalid. Despite completing all requirements?

**Review by Gambit142 — COMMENTED** [review]
Hi @fmanimashaun @Ademola-coding 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Great work using a collaborative tool to complete this task but in Microverse, having co-authored commits is not allowed. I would advise you to close this pull request, open a new one and individually make commits until you implement all requirements. 👍 😎 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Munsa1** [comment]
Hey @fmanimashaun  feel free to ask for a second opinion, but I reached out to a senior code reviewer concerning this matter and they told me you guys have to make separate commits so as for both your contributions to register.

You can see below your partner is not being seen as a contributor
image

**Comment by fmanimashaun** [comment]
@Munsa1 doesn't make sense, we work collaboratively using the available technologies, slack chats and live sharing via vscode

**Comment by nicupop729** [comment]
Hello @fmanimashaun,

My name is Nicolae Pop, and I am a senior code reviewer.

Please note that in pair-programming activities, we expect that the driver-navigator roles are respected. So first, one student is coding, and their partner will navigate them on Zoom, build a feature in the project, push the commit, and then reverse the roles. The student, who previously was a navigator, can now be the driver, and his peer will be a navigator this time. And students need to switch roles like this until all project requirements are completed.

Using co-authored commits means that one student will always be the driver and will add their peer name and GitHub account to the commit name, which is not enough for us to evaluate the contribution of each student. Plus, the driver-navigator roles are not followed.

I hope it makes more sense now why we cannot accept co-authored commits.

Thank you, and happy coding!

**Pull request merged**
